# This file contains the connection profile for dbt to connect to Snowflake.
# In production, sensitive values should be stored as environment variables.

dbt_walmart:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE', 'ETL') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE', 'WALM_DATA') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'ETL') }}"
      schema: mart
      threads: 4
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE', 'ETL') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE', 'WALM_DATA') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'ETL') }}"
      schema: mart
      threads: 8
      client_session_keep_alive: False
