-- Minimal Snowflake Setup for dbt
-- Run this in Snowflake before running dbt

-- Create the main database
CREATE DATABASE IF NOT EXISTS WALM_DATA;
USE DATABASE WALM_DATA;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS MART;

-- RAW tables (without S3 pipes - we'll load CSV manually or via dbt seeds)
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.DEPARTMENT (
    STORE INT,
    DEPT INT,
    DATE DATE,
    WEEKLY_SALES DECIMAL(18,2),
    ISHOLIDAY VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.FACT (
    STORE INT,
    DATE DATE,
    TEMPERATURE DECIMAL(10,2),
    FUEL_PRICE DECIMAL(10,3),
    MARKDOWN1 DECIMAL(18,2),
    MARKDOWN2 DECIMAL(18,2),
    MARKDOWN3 DECIMAL(18,2),
    MARKDOWN4 DECIMAL(18,2),
    MARKDOWN5 DECIMAL(18,2),
    CPI DECIMAL(18,7),
    UNEMPLOYMENT DECIMAL(10,3),
    ISHOLIDAY VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.STORES (
    STORE INT,
    TYPE VARCHAR(10),
    SIZE INT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Now load your CSV data into these tables
-- You can use COPY INTO or Snowflake's web UI to upload CSVs
